export type RectMode = 'normal' | 'hint';
export type EditorMode = 'edit' | 'practice';
export type Phase = 'requesting_workspace' | 'recent_projects' | 'selecting_workspace_for_create' | 'selecting_image_for_create' | 'creating_project' | 'opening_project' | 'selecting_workspace_for_import' | 'selecting_zip_for_import' | 'editor_editing' | 'editor_practice' | 'confirming_project_switch' | 'saving' | 'importing_zip' | 'exporting_zip' | 'deleting_project' | 'conflict_pending' | 'error';
export interface MaskRect { id: string; name: string; mode: RectMode; x: number; y: number; width: number; height: number; rotation: number; fill: {color:string}; stroke: {color:string;width:number}; contentText: {value:string;fontSize:number;color:string}; hintText: string }
export interface Project { schemaVersion:1; projectId:string; title:string; directoryName?:string; revision?:number; lastWriterId?:string; createdAt:string; updatedAt:string; lastOpenedAt:string; sourceImage:{path:string;mimeType:string;width:number;height:number}; canvas:{width:number;height:number;background:string}; rectangles:MaskRect[] }
export interface ProjectView { project:Project; imageUrl:string; imageBlob:Blob; thumbnailUrl:string; baseHash?:string }
export interface RecentProject { projectId:string; title:string; createdAt:string; lastOpenedAt:string; thumbnailUrl:string }
export const uid = () => crypto.randomUUID();
const pad=(value:number)=>String(value).padStart(2,'0');
export const now = () => {const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`};
export type DiagnosticEventName='save_started'|'save_written'|'save_readback'|'save_verified'|'save_failed'|'project_created'|'project_switched'|'project_deleted';
export type DiagnosticResult='started'|'success'|'failed'|'skipped';
export interface DiagnosticEvent {schemaVersion:1;runId:string;sequence:number;timestamp:string;event:DiagnosticEventName;phase:string;projectId:string;editVersion:number;rectangleCount:number;snapshotHash?:string;persistedHash?:string;workspaceId?:string;writerId?:string;operationId?:string;writeSource?:'create'|'edit'|'import'|'rename'|'unknown';directoryName?:string;baseHash?:string;diskHashAfterWrite?:string;diskHashOnSwitch?:string;revision?:number;baseRevision?:number;fileSize?:number;fileLastModified?:number;readbackSource?:'fresh_handle'|'stable_fresh_handle'|'native_service';targetFile?:string;pendingFile?:string;commitPhase?:'pending_written'|'pending_verified'|'backup_written'|'final_replaced'|'final_verified'|'native_atomic_committed'|'native_atomic_verified';expectedRevision?:number;actualRevision?:number;serviceWorkspace?:string;servicePid?:number;requestSource?:string;conflictStage?:string;rollbackDetected?:boolean;conflictCode?:string;result:DiagnosticResult;errorCode?:string|null}
export function uniqueName(requested:string, rectangles:MaskRect[], exceptId?:string):string {const names=new Set(rectangles.filter(r=>r.id!==exceptId).map(r=>r.name));const base=requested.trim()||'矩形';if(!names.has(base))return base;let i=2;while(names.has(`${base} ${i}`))i++;return `${base} ${i}`}
export function newRect(project:Project,x:number,y:number):MaskRect {let i=1;while(project.rectangles.some(r=>r.name===`矩形 ${i}`))i++;return{id:uid(),name:`矩形 ${i}`,mode:'normal',x:Math.round(x),y:Math.round(y),width:Math.min(180,project.canvas.width),height:Math.min(110,project.canvas.height),rotation:0,fill:{color:'#ffffff'},stroke:{color:'#000000',width:2},contentText:{value:'',fontSize:24,color:'#000000'},hintText:''}}
const hex=/^#[0-9a-fA-F]{6}$/;
const finite=(v:unknown)=>typeof v==='number'&&Number.isFinite(v);
export function validateProject(value:unknown):Project {if(!value||typeof value!=='object')throw Error('项目 JSON 无效');const p=value as Project;if(p.schemaVersion!==1||typeof p.projectId!=='string'||!/^[a-f0-9-]{36}$/i.test(p.projectId)||typeof p.title!=='string'||p.title.length>200||!p.canvas||!p.sourceImage||!Array.isArray(p.rectangles))throw Error('项目结构或版本不受支持');if(p.revision!==undefined&&(!Number.isInteger(p.revision)||p.revision<0)||p.lastWriterId!==undefined&&typeof p.lastWriterId!=='string')throw Error('项目修订信息无效');if(!Number.isInteger(p.canvas.width)||!Number.isInteger(p.canvas.height)||p.canvas.width<8||p.canvas.height<8||p.canvas.width>20000||p.canvas.height>20000||!hex.test(p.canvas.background))throw Error('画布参数无效');if(!Number.isInteger(p.sourceImage.width)||!Number.isInteger(p.sourceImage.height)||p.sourceImage.width<1||p.sourceImage.height<1||p.sourceImage.width>20000||p.sourceImage.height>20000||!/^assets\/original\.(png|jpg|webp)$/.test(p.sourceImage.path)||!['image/png','image/jpeg','image/webp'].includes(p.sourceImage.mimeType))throw Error('图片引用无效');if(p.rectangles.length>10000)throw Error('矩形数量过多');const ids=new Set<string>(),names=new Set<string>();for(const r of p.rectangles){if(!r||typeof r.id!=='string'||typeof r.name!=='string'||!r.name.trim()||r.name.length>120||ids.has(r.id)||names.has(r.name)||!['normal','hint'].includes(r.mode)||![r.x,r.y,r.width,r.height,r.rotation,r.stroke?.width,r.contentText?.fontSize].every(finite)||r.width<8||r.height<8||r.width>20000||r.height>20000||r.stroke.width<0||r.stroke.width>100||r.contentText.fontSize<1||r.contentText.fontSize>1000||![r.fill?.color,r.stroke?.color,r.contentText?.color].every(v=>typeof v==='string'&&hex.test(v))||typeof r.contentText.value!=='string'||typeof r.hintText!=='string')throw Error('矩形属性无效');ids.add(r.id);names.add(r.name)}return p}
export function displayState(mode:RectMode,step:number):'visible'|'hint'|'revealed' {if(mode==='normal')return step%2===1?'revealed':'visible';return step%3===1?'hint':step%3===2?'revealed':'visible'}
